### ISSUE TITLE
NVR to WGEO have alot of stretched meshes.

### ISSUE THREAD

**Issue by TheKillerey** [LoL-Fantome/Fantome.Libraries.League#78]
![desktop screenshot 2019 01 30 - 19 44 54 95](https://user-images.githubusercontent.com/18242778/52127615-dda04800-2632-11e9-84cc-a9073d1f9080.png)
![unknown](https://user-images.githubusercontent.com/18242778/52127643-f9a3e980-2632-11e9-8bfd-f6d532b8693d.png)

I used the test code for it

**Comment by ChewyBomber** [comment]
Fixed by 6dbd0c2d4c22795cae4d6dfd34bee58f03f1be4e
