### ISSUE TITLE
MOBObject

### ISSUE THREAD

**Issue by horato** [LoL-Fantome/Fantome.Libraries.League#84]
https://github.com/LoL-Fantome/Fantome.Libraries.League/blob/c49c5d373b70c12bd53e074ad8a6fcfeb011f6f7/Fantome.League/IO/MapObjects/MOBObject.cs#L71

Should be 62 bytes name, 1 byte type, 1 byte ignore collision flag

**Comment by Crauzer** [comment]
#86 #85 fixed 👍
