### ISSUE TITLE
Mapgeo: X and Y are zero after importing it

### ISSUE THREAD

**Issue by TheKillerey** [LoL-Fantome/Fantome.Libraries.League#93]
```
System.NullReferenceException: "Object reference not set to an instance of an object."

"x" was "zero".
```
Happens when open the .mapgeo file.

**Comment by Crauzer** [comment]
What do you mean by X and Y

**Comment by TheKillerey** [comment]
![image](https://user-images.githubusercontent.com/18242778/75613450-27a57700-5b2e-11ea-929c-b77224d3d651.png)
It gives me this

**Comment by Crauzer** [comment]
fixed
