### ISSUE TITLE
Export Yone champion model error if include animation 

### ISSUE THREAD

**Issue by lingme** [LoL-Fantome/Fantome.Libraries.League#97]
I try export Yone, include "\assets\characters\yone\skins\base\animations\yone_idle01.yone.anm" animation, 
![image](https://user-images.githubusercontent.com/32844254/91800619-e2d4d700-ec5b-11ea-8703-d02131b86934.png)
done, I try to open with Blender or Gltf-viewer error
![image](https://user-images.githubusercontent.com/32844254/91800776-31827100-ec5c-11ea-811e-233d8147f998.png)
I tried it does not include the animation, it is normal to work

**Comment by lingme** [comment]
I support for program made some small changes, parameterized
```csharp
static void Main(string[] args)
        {
            SimpleSkin skn = new SimpleSkin(args[0]);
            List<(string, LeagueAnimation)> animationList = new List<(string, LeagueAnimation)>();
            ModelRoot gltf;
            if (args.Count() > 3)
            {
                for (int i = 3; i < args.Count(); i++)
                {
                    animationList.Add(($"animation{animationList.Count + 1}", new LeagueAnimation(args[i])));
                }
                gltf = skn.ToGltf(new Skeleton(args[1]), animationList);
            }
            else
            {
                gltf = skn.ToGltf(new Skeleton(args[1]));
            }

            gltf.SaveGLTF(args[2]);

            Console.WriteLine("Convert successful! Press any key to exit");
            Console.ReadLine();
        }
```

**Comment by Crauzer** [comment]
Animations are not yet fully supported, please wait until all the work for the `Animation` class is finished

**Comment by lingme** [comment]
Thank you so much for the epic work contribution

**Comment by Crauzer** [comment]
5a185bdb3e56a35b553db569443b768409ec0134

**Comment by lingme** [comment]
I browser code see animation version 3 and 4 not implementation , is Because none of the animation contains both versions？

**Comment by Crauzer** [comment]
Not really, I'm writing a V4 parser right now.

Both versions still exist in league, they are just not as common as V5 and Canm.

**Comment by lingme** [comment]
You are very amazing

**Comment by Crauzer** [comment]
18a25215e4ec1f212d7184d7230ba2023176978e

**Comment by lingme** [comment]
hah，Your speed of support has exceeded the limit

**Comment by lingme** [comment]
I have contributed a cup of coffee to you, Let us congratulate your contribution，good night
