### ISSUE TITLE
Export Kayn champion model error if include animation

### ISSUE THREAD

**Issue by lingme** [LoL-Fantome/Fantome.Libraries.League#98]
![image](https://user-images.githubusercontent.com/32844254/91873657-dbd5b500-ecab-11ea-81f8-27ee4d32905a.png)
I try to export Kayn for including animate but throws an unhandled exception

**Comment by Crauzer** [comment]
Use [this](https://github.com/LoL-Fantome/Fantome.Libraries.League/blob/master/Fantome.Libraries.League/IO/AnimationFile/Animation.cs#L404) function to determine if an animation is compatible with a specific skeleton.

I will change this behavior soon 👍🏼

**Comment by lingme** [comment]
thanks, I will try this method.
